name: UltraItemLock
version: 1.2.5
main: me.pixelmaniastudios.itemlock.Main
api-version: 1.16
commands:
  lock:
    description: Lock an item in hand
    usage: /lock
    aliases: [slotlock, lockslot]
  unlock:
    description: Unlock an item in hand
    usage: /unlock
    aliases: [slotunlock, unlockslot]
  ultraitemlockreload:
    description: Reload the plugin configuration.
    usage: /ultraitemlockreload
    permission: itemlock.reload
    aliases: [uilreload]
    
permissions:
  itemlock.reload:
    description: Allows a player to execute administrative commands for Itemlock
    default: op
